---
name: CI

on:
  push:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.5", "3.0", "3.1"]
        rust: ["stable", "beta"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run ruby tests
        run: bundle exec rake

      - name: Lint rust
        working-directory: ./ext/rweb3
        run: cargo clippy && cargo fmt --check
