---
name: CI

on:
  push:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.5", "3.0", "3.1", "head"]
        rust: ["stable", "beta"]
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          bundler-cache: true
          cargo-cache: true

      - name: Run ruby tests
        run: bundle exec rake

      - name: Lint rust
        working-directory: .ext/rweb3
        run: cargo clippy && cargo fmt --check
