---
name: CI

on:
  push:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.5", "3.0", "3.1"]
        rust: ["stable", "beta"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          path: tmp

      - run: bundle exec rake compile

      - uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          path: tmp

      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ext/rweb3/Cargo.toml

      - name: Run ruby tests
        run: bundle exec rake

